packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@sentry-internal/node-cpu-profiler": true
  "@sentry/cli": true
  core-js: false
  protobufjs: false
onlyBuiltDependencies:
  - lefthook
  - esbuild
  - sharp
  - msgpackr-extract
  - "@sentry/cli"
  - "@sentry-internal/node-cpu-profiler"
